# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/brandon.hahn/ee324_game_vivado_school_computer/ee324_game_vivado_school_computer.srcs/sources_1/bd/brandonBlockDesign/ip/brandonBlockDesign_xbar_1/brandonBlockDesign_xbar_1.xci
# IP: The module: 'brandonBlockDesign_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/brandon.hahn/ee324_game_vivado_school_computer/ee324_game_vivado_school_computer.gen/sources_1/bd/brandonBlockDesign/ip/brandonBlockDesign_xbar_1/brandonBlockDesign_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'brandonBlockDesign_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/brandon.hahn/ee324_game_vivado_school_computer/ee324_game_vivado_school_computer.srcs/sources_1/bd/brandonBlockDesign/ip/brandonBlockDesign_xbar_1/brandonBlockDesign_xbar_1.xci
# IP: The module: 'brandonBlockDesign_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/brandon.hahn/ee324_game_vivado_school_computer/ee324_game_vivado_school_computer.gen/sources_1/bd/brandonBlockDesign/ip/brandonBlockDesign_xbar_1/brandonBlockDesign_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'brandonBlockDesign_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
