# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/brandon.hahn/Downloads/ee324Game-brandonBranch/ee324Game-brandonBranch/BlackboardRevB_MasterXDC.xdc

# Block Designs: bd/brandonBlockDesign/brandonBlockDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign || ORIG_REF_NAME==brandonBlockDesign} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_processing_system7_0_0/brandonBlockDesign_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_processing_system7_0_0 || ORIG_REF_NAME==brandonBlockDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_brandon_led_ip_0_0/brandonBlockDesign_brandon_led_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_brandon_led_ip_0_0 || ORIG_REF_NAME==brandonBlockDesign_brandon_led_ip_0_0} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_rst_ps7_0_50M_0/brandonBlockDesign_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_rst_ps7_0_50M_0 || ORIG_REF_NAME==brandonBlockDesign_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_brandonInputIP_0_0/brandonBlockDesign_brandonInputIP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_brandonInputIP_0_0 || ORIG_REF_NAME==brandonBlockDesign_brandonInputIP_0_0} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_hdmi_tx_0_0/brandonBlockDesign_hdmi_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_hdmi_tx_0_0 || ORIG_REF_NAME==brandonBlockDesign_hdmi_tx_0_0} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_clk_wiz_0_1/brandonBlockDesign_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_clk_wiz_0_1 || ORIG_REF_NAME==brandonBlockDesign_clk_wiz_0_1} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_brandon_height_and_w_0_4/brandonBlockDesign_brandon_height_and_w_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_brandon_height_and_w_0_4 || ORIG_REF_NAME==brandonBlockDesign_brandon_height_and_w_0_4} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_brandonColors_0_1/brandonBlockDesign_brandonColors_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_brandonColors_0_1 || ORIG_REF_NAME==brandonBlockDesign_brandonColors_0_1} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_gameTopMod_0_1/brandonBlockDesign_gameTopMod_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_gameTopMod_0_1 || ORIG_REF_NAME==brandonBlockDesign_gameTopMod_0_1} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_xbar_1/brandonBlockDesign_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_xbar_1 || ORIG_REF_NAME==brandonBlockDesign_xbar_1} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_ps7_0_axi_periph_1/brandonBlockDesign_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_ps7_0_axi_periph_1 || ORIG_REF_NAME==brandonBlockDesign_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_brandon_height_and_w_0_5/brandonBlockDesign_brandon_height_and_w_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_brandon_height_and_w_0_5 || ORIG_REF_NAME==brandonBlockDesign_brandon_height_and_w_0_5} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_brandon_height_and_w_0_6/brandonBlockDesign_brandon_height_and_w_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_brandon_height_and_w_0_6 || ORIG_REF_NAME==brandonBlockDesign_brandon_height_and_w_0_6} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_brandon_height_and_w_0_7/brandonBlockDesign_brandon_height_and_w_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_brandon_height_and_w_0_7 || ORIG_REF_NAME==brandonBlockDesign_brandon_height_and_w_0_7} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_pixGenSource_0_1/brandonBlockDesign_pixGenSource_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_pixGenSource_0_1 || ORIG_REF_NAME==brandonBlockDesign_pixGenSource_0_1} -quiet] -quiet

# IP: bd/brandonBlockDesign/ip/brandonBlockDesign_auto_pc_0/brandonBlockDesign_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==brandonBlockDesign_auto_pc_0 || ORIG_REF_NAME==brandonBlockDesign_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/brandon.hahn/ee324_game_vivado_school_computer/ee324_game_vivado_school_computer.gen/sources_1/bd/brandonBlockDesign/brandonBlockDesign_ooc.xdc
